CREATE TABLE respuestas (
	id int(11) NOT NULL AUTO_INCREMENT,
	fecha datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	respuesta varchar(2048) NOT NULL,
	idMensaje int(11) NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;